version: "3.8"

services:
  cheapp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cheapp-backend

    expose:
      - "8002"        # 仅供同网络容器访问
    ports:
      - "8002:8002"   # 若不需要宿主机调试，可删掉这两行

    restart: always
    networks:
      - app-network

networks:
  app-network:
    external: true
